name: google_auth_repository
description: Dart package which manages the authentication domain.
version: 1.0.1

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  google_sign_in: "^5.1.1"
  flutter:
    sdk: flutter

dev_dependencies:
    flutter_lints: ^1.0.4