name: club_cloud
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.0
  beamer: ^0.14.1
  equatable: ^2.0.3
  firebase_core: "^1.7.0"
  firebase_auth: "^3.1.3"
  formz: ^0.4.0
  font_awesome_flutter: ^9.1.0
  path_provider: ^2.0.5

  firebase_auth_repository:
    path: packages/firebase_auth_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

